version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:latest
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: rialto_test

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/sul-dlss-labs/rialto-derivatives
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get github.com/golang/dep/cmd/dep
      - run: dep ensure
      - run:
          name: Install PG client
          command: sudo apt-get install postgresql-client
      - run: psql -h localhost -p 5432 rialto_test < database.dump
      - run: go test -v ./...
